--- 
  aws:
    regions:
      - us-east-1
      - us-west-2
      - ap-northeast-1
      - eu-west-1

    enabled_reports:
      - ec2
      - rds  

  google_sheets:
    sheet_name: Reserved Instances Analyzer
