"""Make resource DateTime columns timezone-aware

Revision ID: 29fd4aae9e1f
Revises: 47ff405c076f
Create Date: 2020-04-27 15:16:27.667674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29fd4aae9e1f'
down_revision = '47ff405c076f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
