"""Make reservation DateTime columns timezone-aware

Revision ID: 47ff405c076f
Revises: a0efdd21fb7f
Create Date: 2020-04-27 15:14:34.760934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47ff405c076f'
down_revision = 'a0efdd21fb7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
