"""Initial version

Revision ID: aa7bb1ca567b
Revises: 
Create Date: 2020-04-27 17:44:14.148732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa7bb1ca567b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('availability_zone', sa.String(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('account_name', sa.String(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('instance_class', sa.String(), nullable=True),
    sa.Column('normalized_capacity_each', sa.Integer(), nullable=True),
    sa.Column('normalized_capacity_total', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('multi_az', sa.Boolean(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fixed_price', sa.Float(), nullable=True),
    sa.Column('usage_price', sa.Float(), nullable=True),
    sa.Column('recurring_charges', sa.Float(), nullable=True),
    sa.Column('offering_class', sa.String(), nullable=True),
    sa.Column('offering_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tag_group', sa.String(), nullable=True),
    sa.Column('account_name', sa.String(), nullable=True),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('availability_zone', sa.String(), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('normalized_capacity', sa.Integer(), nullable=True),
    sa.Column('image_id', sa.String(), nullable=True),
    sa.Column('instance_type', sa.String(), nullable=True),
    sa.Column('launch_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('private_ip_address', sa.String(), nullable=True),
    sa.Column('public_ip_address', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('subnet_id', sa.String(), nullable=True),
    sa.Column('vpc_id', sa.String(), nullable=True),
    sa.Column('architecture', sa.String(), nullable=True),
    sa.Column('hypervisor', sa.String(), nullable=True),
    sa.Column('engine', sa.String(), nullable=True),
    sa.Column('multi_az', sa.Boolean(), nullable=True),
    sa.Column('allocated_storage', sa.Float(), nullable=True),
    sa.Column('iops', sa.Integer(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resources')
    op.drop_table('reservations')
    # ### end Alembic commands ###
